name: Test and Deploy
on:
  - push
jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Set-up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Requirements
        run: make requirements
      - name: Setup Dev Environment
        run: make dev-setup
      - name: Create AWS Creds
        run: mkdir ~/.aws && touch ~/.aws/credentials && echo -e "[default]\naws_access_key_id = test\naws_secret_access_key = test\naws_default-region = eu-west-2" > ~/.aws/credentials
      - name: Run Security Test
        run: make security-test
      - name: Run Flake8 Code Check
        run: make flake
      - name: Run Coverage Check
        run: make check-coverage
  run-unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Set-up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Requirements
        run: make requirements
      - name: Run Unit Test
        run: make unit-test
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Initialised Terraform
        working-directory: terraform
        run: terraform init
      - name: Plan Terraform
        working-directory: terraform
        run: terraform plan
      - name: Apply Terraform
        working-directory: terraform
        run: terraform apply -auto-approve